services:
  # This defines your web service
  - type: web
    name: shared-browser # You can change this name
    # Tell Render to use Docker for the environment
    runtime: docker
    # Specify the path to your Dockerfile
    dockerfilePath: ./Dockerfile
    # Set up health checks
    healthCheckPath: /health
    # Define environment variables if needed
    envVars:
      - key: PYTHON_VERSION
        value: 3.11 # This is more for documentation; the Dockerfile sets the version
