# render.yaml
# This is the definitive configuration file for Render.

services:
  - type: web
    name: python-web-visitor
    
    # This tells Render to build your application using the Dockerfile.
    env: docker
    
    # Set this to the paid plan you upgraded to (e.g., 'starter').
    plan: starter
    
    # The 'startCommand' has been removed, as it is not allowed with 'env: docker'.
    # Render will now use the CMD instruction from the Dockerfile.
    
    # Optional: Increase the health check timeout.
    healthCheckPath: /
